TEMPLATE     = vcapp
TARGET       = Super2048
CONFIG      += warn_on qt debug_and_release windows console
HEADERS     += Tableau.h Jeu.h Affichage.h Tuile.h Grille.h Joueur.h
SOURCES     += 2048-Console.cpp Tableau.cpp Jeu.cpp Affichage.cpp Tuile.cpp Grille.cpp Joueur.cpp
INCLUDEPATH += Ressources\Assets\
LIBS	    += 
RESOURCES    = Resource.qrc
QT += widgets gui
